version: "2.4"
services:
  mockServer:
    image: mockserver/mockserver:5.14.0
    ports:
      - 80:1080
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /envmondata/data.json
    volumes:
      - type: bind
        source: .
        target: /envmondata
