name: Build and run tests

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  dev-system-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install GCC and Valgrind
        run: |
          sudo apt-get install -y gcc valgrind
      - name: Build tests (development target)
        run: |
          make tests
      - name: Run tests and check for memory leaks
        run: |
          valgrind --leak-check=full -s --error-exitcode=1 ./tests-dev -r 3
      - name: Create test coverage report
        run: |
          ./.github/scripts/create-test-coverage-report.sh >> $GITHUB_STEP_SUMMARY


  # todo: Publish the resulting program to github releases when more polished and working
  amiga-m68k-build:
    runs-on: ubuntu-latest
    container: themkat/amigaosm68k:latest
    steps:
      - name: Install lhasa dependency
        run: |
          sudo apt-get install -y lhasa
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build main application
        run: |
          make AmiEnvMon -e OS=os3
      - name: Build tests
        run: |
          make tests -e OS=os3
      - name: Create lha archive
        if: ${{ github.ref_type == 'tag' }}
        run: |
          lha a AmiEnvMon-OS3.lha AmiEnvMon
          lha a AmiEnvMon-OS3.lha amienvmon.png
          lha a AmiEnvMon-OS3.lha tests-os3
      - uses: actions/upload-artifact@v3
        if: ${{ github.ref_type == 'tag' }}
        with:
          name: AmiEnvMon-OS3
          path: AmiEnvMon-OS3.lha

  amiga-ppc-build:
    runs-on: ubuntu-latest
    container: amigadev/crosstools:ppc-amigaos
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      # - name: Build main application
      #   run: |
      #     make AmiEnvMon -e OS=os4
      - name: Build tests
        run: |
          make tests -e OS=os4
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: AmiEnvMon-OS4
      #     path: |
      #       AmiEnvMon
      #       amienvmon.png
      #       tests-os4

  release:
    runs-on: ubuntu-latest
    needs: [dev-system-tests, amiga-m68k-build, amiga-ppc-build]
    if: ${{ github.ref_type == 'tag' }}
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: AmiEnvMon-OS3
      - uses: ncipollo/release-action@v1
        with:
          name: AmiEnvMon ${{ github.ref_name }}
          body: ""
          artifacts: "AmiEnvMon-OS3.lha"
          tag: ${{ github.ref }}
