name: Build and run tests

on: [push]

jobs:
  dev-system-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install GCC and Valgrind
        run: |
          sudo apt-get install -y gcc valgrind
      - name: Build tests (development target)
        run: |
          make tests
      - name: Run tests and check for memory leaks
        run: |
          valgrind --leak-check=full -s --error-exitcode=1 ./tests-dev -r 3


  # todo: Publish the resulting program to github releases when more polished and working
  amiga-m68k-build:
    runs-on: ubuntu-latest
    container: themkat/amigaosm68k:latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build main application
        run: |
          make AmiEnvMon -e OS=os3
      - name: Build tests
        run: |
          make tests -e OS=os3

      - uses: actions/upload-artifact@v3
        # TODO: better artifact name?
        with:
          name: AmiEnvMon-OS3
          path: |
            AmiEnvMon
            amienvmon.png
            tests-os3

  amiga-ppc-build:
    runs-on: ubuntu-latest
    container: amigadev/crosstools:ppc-amigaos
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build main application
        run: |
          make AmiEnvMon -e OS=os4
      - name: Build tests
        run: |
          make tests -e OS=os4
      - uses: actions/upload-artifact@v3
        with:
          name: AmiEnvMon-OS4
          path: |
            AmiEnvMon
            amienvmon.png
            tests-os4

